#Ansible Jenkins Master, sample playbook - jenkins-master-sample.yml
---
- hosts: "{{ passed_in_hosts }}"
  become: yes
  become_user: root
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: present

    - name: Start and Enable Apache
      service:
        name: httpd
        state: started
        enabled: yes
